import pytest

from asrom_llm.pubmed_search import (
    filter_split_parsed_data_into_doc_format,
    parse_result,
    search_pubmed,
)


@pytest.fixture
def query():
    return "non‐pharmacological interventions for headache in children and adolescents"


@pytest.fixture
def records():
    record = [
        {
            "PMID": "35660103",
            "OWN": "NLM",
            "STAT": "MEDLINE",
            "DCOM": "20220719",
            "LR": "20220719",
            "IS": "1532-2130 (Electronic) 1090-3798 (Linking)",
            "VI": "39",
            "DP": "2022 Jul",
            "TI": "Repetitive neuromuscular magnetic stimulation in children with headache.",
            "PG": "40-48",
            "LID": "S1090-3798(22)00066-6 [pii] 10.1016/j.ejpn.2022.04.010 [doi]",
            "AB": "INTRODUCTION: Repetitive neuromuscular magnetic stimulation (rNMS) was previously applied in adult patients with episodic migraine, showing beneficial effects on headache characteristics, high safety, and convincing satisfaction. This study aims to assess rNMS as a personalized intervention in pediatric headache. METHODS: Retrospective chart review including patients with migraine, TTH, mixed type headache, or PTH, who had received at least one test rNMS session targeting the upper trapezius muscles (UTM). RESULTS: 33 patients (13.9 +/- 2.5 years; 61% females) were included in the primary analysis, resulting in a total of 182 rNMS sessions. 43 adverse events were documented for 40 of those sessions (22%). Most common side effects were tingling (32.6%), muscle sore (25.5%), shoulder (9.3%) and back pain (9.3%). Secondly, in patients (n = 20) undergoing the intervention, headache frequency (p = 0.017) and minimum and maximum intensities (p = 0.017; p = 0.023) significantly decreased from baseline to 3-month after intervention. 11 patients (44%) were classified as >/=25% responders, with 7 patients (28%) experiencing a >/=75% reduction of headache days. After 73% of interventions, patients reported rNMS helped very well or well. A majority of patients would repeat (88.5%) and recommend rNMS (96.2%) to other patients. CONCLUSION: rNMS seems to meet the criteria of safety, feasibility, and acceptance among children and adolescents with three age-typical headache disorders. A significant reduction in headache frequency and intensity during a 3 months follow-up was documented. Larger, prospective, randomized, sham-controlled studies are urgently needed to confirm if rNMS may become a new valuable non-invasive, non-pharmacological treatment option for pediatric headache disorders.",
            "CI": [
                "(c) 2022 Published by Elsevier Ltd on behalf of European Paediatric Neurology",
                "Society.",
            ],
            "FAU": [
                "Staisch, Jacob",
                "Borner, Corinna",
                "Lang, Magdalena",
                "Hauser, Ari",
                "Hannibal, Iris",
                "Huss, Kristina",
                "Klose, Birgit",
                "Lechner, Matthias F",
                "Sollmann, Nico",
                "Heinen, Florian",
                "Landgraf, Mirjam N",
                "Bonfert, Michaela V",
            ],
            "AU": [
                "Staisch J",
                "Borner C",
                "Lang M",
                "Hauser A",
                "Hannibal I",
                "Huss K",
                "Klose B",
                "Lechner MF",
                "Sollmann N",
                "Heinen F",
                "Landgraf MN",
                "Bonfert MV",
            ],
            "AD": [
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany; Department of Diagnostic and Interventional Neuroradiology, School of Medicine, Klinikum Rechts der Isar, Technical University of Munich, Munich, Germany; TUM-Neuroimaging Center, Klinikum Rechts der Isar, Technical University of Munich, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "Department of Diagnostic and Interventional Neuroradiology, School of Medicine, Klinikum Rechts der Isar, Technical University of Munich, Munich, Germany; TUM-Neuroimaging Center, Klinikum Rechts der Isar, Technical University of Munich, Munich, Germany; Department of Diagnostic and Interventional Radiology, University Hospital Ulm, Ulm, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany.",
                "LMU Hospital, Department of Pediatrics - Dr. von Hauner Children's Hospital, Division of Pediatric Neurology and Developmental Medicine, Ludwig-Maximilians University, Munich, Germany; LMU Center for Children with Medical Complexity - iSPZ Hauner, Ludwig-Maximilians University, Munich, Germany. Electronic address: michaela.bonfert@med.lmu.de.",
            ],
            "LA": ["eng"],
            "PT": ["Journal Article"],
            "DEP": "20220506",
            "PL": "England",
            "TA": "Eur J Paediatr Neurol",
            "JT": "European journal of paediatric neurology : EJPN : official journal of the European Paediatric Neurology Society",
            "JID": "9715169",
            "SB": "IM",
            "MH": [
                "Adolescent",
                "Adult",
                "Child",
                "Female",
                "Headache/therapy",
                "*Headache Disorders",
                "Humans",
                "Magnetic Phenomena",
                "Male",
                "*Migraine Disorders/therapy",
                "Prospective Studies",
                "Retrospective Studies",
            ],
            "OTO": ["NOTNLM"],
            "OT": [
                "Adherence",
                "Feasibility",
                "Migraine",
                "Neuromodulation",
                "Neurostimulation",
                "Post-traumatic headache",
                "Safety",
                "Tension-type headache",
            ],
            "EDAT": "2022/06/07 06:00",
            "MHDA": "2022/07/20 06:00",
            "CRDT": ["2022/06/06 11:19"],
            "PHST": [
                "2022/01/19 00:00 [received]",
                "2022/03/20 00:00 [revised]",
                "2022/04/27 00:00 [accepted]",
                "2022/06/07 06:00 [pubmed]",
                "2022/07/20 06:00 [medline]",
                "2022/06/06 11:19 [entrez]",
            ],
            "AID": [
                "S1090-3798(22)00066-6 [pii]",
                "10.1016/j.ejpn.2022.04.010 [doi]",
            ],
            "PST": "ppublish",
            "SO": "Eur J Paediatr Neurol. 2022 Jul;39:40-48. doi: 10.1016/j.ejpn.2022.04.010. Epub 2022 May 6.",
        },
        {
            "PMID": "35120753",
            "OWN": "NLM",
            "STAT": "MEDLINE",
            "DCOM": "20220608",
            "LR": "20220608",
            "IS": "0013-7006 (Print) 0013-7006 (Linking)",
            "VI": "48",
            "IP": "3",
            "DP": "2022 Jun",
            "TI": "[Therapeutic approaches for sleep and rhythms disorders in children with ASD].",
            "PG": "294-303",
            "LID": "S0013-7006(21)00217-7 [pii] 10.1016/j.encep.2021.08.005 [doi]",
            "AB": "Sleep disturbances are extremely common (40-86%) in children and adolescents, especially those with autism spectrum disorders (ASD) and are often among the first symptoms identified by parents at a very early stage of their child's development. These abnormalities are among the main parental concerns when having a child with ASD and have a significant impact on the quality of life of patients, their parents, and more broadly their siblings. Sleep disorders are essentially abnormalities of the sleep-wake rhythm - primarily sleep onset insomnia or nocturnal awakenings (with difficulty falling back to sleep). These disturbances can be accompanied by other sleep disorders, requiring notably a systematic elimination of the presence of a sleep apnea or restless legs syndrome - to ensure a personalized and efficient therapeutic approach. Physiologically, the determinants of these sleep disorders are poorly understood, even though several studies point to a significant decrease in melatonin synthesis in people with ASD. Melatonin is a hormone that facilitates falling asleep and maintaining sleep and is also involved in the endogenous synchronization of internal biological clocks. However, the causal factors of this decrease in melatonin synthesis are largely unknown, involving to a small extent the genes involved in melatonin synthesis pathway. The treatment of sleep disorders is relatively systematic: after eliminating other specific sleep disorders associated with the complaint of insomnia, as well as other possible associated comorbidities (such as seizures), a global and graduated therapeutic approach must be put in place. This treatment will be non-pharmacological as a first line, then pharmacological as a second line. A number of non-pharmacological treatment strategies for sleep disorders in typically developing children and adolescents, as well as those with ASD, have been shown to be effective. This treatment requires a combination of: 1) parental education to promote sleep development; 2) setting up bedtime rituals adapted to the child's age and particularities; 3) specific behavioral strategies including bedtime fading, gradual extinction and positive reinforcement of adapted behaviors. It is very essential that the parents are accompanied throughout this therapy. Sleep hygiene and behavioral care must also take into consideration the important role of the zeitgebers of sleep-wake rhythms, i.e. the external environmental factors involved in the synchronization of the biological clocks: regular exposure to light at adapted times, regular meal and wake-up times, social activities and times for going to school. The evidence for the effectiveness of behavioral interventions in the treatment of behavioral insomnia in the typical developmental child is strong, since 94% of children show clinically significant improvements in nighttime sleepiness and waking. By contrast, only about 25% of children with ASD are improved by an approach combining sleep hygiene and behavioral therapy. Melatonin has a special and prominent place in the drug management of sleep disorders associated with ASD. Several clinical trials have shown that melatonin is effective in treating sleep disorders in patients with ASD. This work led to the European Medicines Agency (EMA) granting marketing authorization in September 2018 for a sustained-release paediatric melatonin molecule (Slenyto(R)). This synthetic molecule is a prolonged release melatonin (PRM) which mimics the physiological pharmacokinetic and secretory characteristics of endogenous melatonin, having a very short blood half-life and prolonged secretion for several hours during the night. A recent study evaluated the efficacy and safety of pediatric PRM (mini-tablets) in 125 children, aged 2 to 17.5 years with mainly ASD. After 15 days on placebo, the children were randomized into two parallel groups, PRM or placebo in a double-blind design for 13 weeks. At endpoint, total sleep time was increased by an average of 57.5 minutes on PRM and only 9.14 minutes on placebo (P=0.034). This difference between the two groups was already significant after three weeks of treatment (P=0.006). Sleep latency was also improved in the PRM group (-39.6 minutes) compared to placebo (-12.51 minutes) (P=0.01). Consolidated sleep duration (uninterrupted by awakenings) was improved by 77.9 minutes for the PRM group and only 25.4 minutes for the placebo group (P<0.001). PRM was well tolerated, the most frequent side effects being headache and daytime drowsiness at the same level with PRM or placebo. In addition, the acceptability by the children for swallowing the mini-tablets was excellent (100% compliance). The efficacy and tolerability of PRM was maintained over the medium and long term in the open phase, over a total study duration of 2 years.",
            "CI": [
                "Copyright (c) 2021 L'Encephale, Paris. Published by Elsevier Masson SAS. All rights",
                "reserved.",
            ],
            "FAU": [
                "Schroder, C M",
                "Broquere, M A",
                "Claustrat, B",
                "Delorme, R",
                "Franco, P",
                "Lecendreux, M",
                "Tordjman, S",
            ],
            "AU": [
                "Schroder CM",
                "Broquere MA",
                "Claustrat B",
                "Delorme R",
                "Franco P",
                "Lecendreux M",
                "Tordjman S",
            ],
            "AD": [
                "Service de psychiatrie de l'enfant et de l'adolescent, centre d'excellence pour l'autisme et les troubles du neurodeveloppement STRAS&ND, hopitaux universitaires de Strasbourg, universite de Strasbourg, 67000 Strasbourg, France; CNRS UPR 3212, institut des neurosciences cellulaires et integratives, 67000 Strasbourg, France; Centre des troubles du sommeil, centre international de recherche en chronosomnologie (CIRCSom), hopitaux universitaires de Strasbourg, 1, place de l'Hopital, 67000 Strasbourg, France. Electronic address: carmen.schroder@chru-strasbourg.fr.",
                "Centre ressource autisme, hopital La Grave Place Lange, 31300 Toulouse, France.",
                "Prosom (association nationale de promotion des connaissances du sommeil), 7, place du Griffon, 69001 Lyon, France.",
                "Service de psychiatrie de l'enfant et de l'adolescent, centre d'excellence pour l'autisme et les troubles du neurodeveloppement inovand, hopital Robert-Debre, 75019 Paris, France; Genetique humaine et fonctions cognitives, institut Pasteur, 75015 Paris, France.",
                "Inserm-U1028, CNRS UMR5292, CRNL, physiologie integree du systeme d'eveil, universite de Lyon 1, Lyon, France; Unite de sommeil pediatrique, hopital Femme Mere Enfant, hospices civils de Lyon, Lyon, France.",
                "Centre pediatrique des pathologies du sommeil, hopital Robert-Debre, 75015 Paris, France; Centre de reference pour la narcolepsie et les hypersomnies idiopathiques et le syndrome de Kleine-Levin (CNR Narcolepsie-Hypersomnie), Paris, France.",
                "Pole hospitalo-universitaire de psychiatrie de l'enfant et de l'adolescent (PHUPEA), centre hospitalier Guillaume-Regnier (CHGR), universite de Rennes 1, Rennes, France; Centre de neurosciences integratives et cognition (CNIC), CNRS UMR 8002, universite de Paris, 75006 Paris, France.",
            ],
            "LA": ["fre"],
            "PT": ["Journal Article", "Randomized Controlled Trial"],
            "TT": "Approches therapeutiques des troubles du sommeil et des rythmes chez l'enfant avec TSA.",
            "DEP": "20220201",
            "PL": "France",
            "TA": "Encephale",
            "JT": "L'Encephale",
            "JID": "7505643",
            "RN": ["JL5DK93RCL (Melatonin)"],
            "SB": "IM",
            "MH": [
                "Adolescent",
                "*Autism Spectrum Disorder/complications",
                "Child",
                "Humans",
                "*Melatonin",
                "Quality of Life",
                "Sleep/physiology",
                "*Sleep Initiation and Maintenance Disorders/etiology/therapy",
                "*Sleep Wake Disorders/complications/therapy",
            ],
            "OTO": ["NOTNLM"],
            "OT": [
                "ASD (Autism Spectrum Disorder)",
                "Behavioural therapy",
                "Children",
                "Enfants",
                "Melatonin",
                "Melatonine",
                "Rhythm disorders",
                "Sleep disorders",
                "TSA (Trouble du Spectre de l'Autisme)",
                "Therapies comportementales",
                "Troubles des rythmes",
                "Troubles du sommeil",
            ],
            "EDAT": "2022/02/06 06:00",
            "MHDA": "2022/06/09 06:00",
            "CRDT": ["2022/02/05 05:36"],
            "PHST": [
                "2021/03/15 00:00 [received]",
                "2021/07/12 00:00 [revised]",
                "2021/08/20 00:00 [accepted]",
                "2022/02/06 06:00 [pubmed]",
                "2022/06/09 06:00 [medline]",
                "2022/02/05 05:36 [entrez]",
            ],
            "AID": [
                "S0013-7006(21)00217-7 [pii]",
                "10.1016/j.encep.2021.08.005 [doi]",
            ],
            "PST": "ppublish",
            "SO": "Encephale. 2022 Jun;48(3):294-303. doi: 10.1016/j.encep.2021.08.005. Epub 2022 Feb 1.",
        },
        {
            "PMID": "34153363",
            "OWN": "NLM",
            "STAT": "MEDLINE",
            "DCOM": "20220913",
            "LR": "20220930",
            "IS": "2352-2291 (Electronic) 0104-0014 (Print) 0104-0014 (Linking)",
            "VI": "72",
            "IP": "5",
            "DP": "2022 Sep-Oct",
            "TI": "Chronic non-cancer pain in adolescents: a narrative review.",
            "PG": "648-656",
            "LID": "S0104-0014(21)00240-2 [pii] 10.1016/j.bjane.2021.04.033 [doi]",
            "AB": "INTRODUCTION: Chronic pain is defined as a pain lasting more than 3-6 months. It is estimated that 25% of the pediatric population may experience some kind of pain in this context. Adolescence, corresponding to a particular period of development, seems to present the ideal territory for the appearance of maladaptive mechanisms that can trigger episodes of persistent or recurrent pain. METHODS: A narrative review, in the PubMed/Medline database, in order to synthetize the available evidence in the approach to chronic pain in adolescents, highlighting its etiology, pathophysiology, diagnosis, and treatment. RESULTS: Pain is seen as a result from the interaction of biological, psychological, individual, social, and environmental factors. Headache, abdominal pain, and musculoskeletal pain are frequent causes of chronic pain in adolescents. Pain not only has implications on adolescents, but also on family, society, and how they interact. It has implications on daily activities, physical capacity, school performance, and sleep, and is associated with psychiatric comorbidities, such as anxiety and depression. The therapeutic approach of pain must be multimodal and multidisciplinary, involving adolescents, their families, and environment, using pharmacological and non-pharmacological strategies. DISCUSSION AND CONCLUSION: The acknowledgment, prevention, diagnosis, and treatment of chronic pain in adolescent patients seem not to be ideal. The development of evidence-based forms of treatment, and the training of health professionals at all levels of care are essential for the diagnosis, treatment, and early referral of these patients.",
            "CI": [
                "Copyright (c) 2021 Sociedade Brasileira de Anestesiologia. Published by Elsevier",
                "Editora Ltda. All rights reserved.",
            ],
            "FAU": [
                "Silva, Carlos",
                "Oliveira, Dora",
                "Pestana-Santos, Marcia",
                "Portugal, Francisco",
                "Capelo, Paula",
            ],
            "AU": [
                "Silva C",
                "Oliveira D",
                "Pestana-Santos M",
                "Portugal F",
                "Capelo P",
            ],
            "AD": [
                "Centro Hospitalar e Universitario de Coimbra, Servico de Anestesiologia, Coimbra, Portugal. Electronic address: carlosreisdasilva@gmail.com.",
                "Centro Hospitalar e Universitario de Coimbra, Servico de Anestesiologia, Departamento de Pediatria, Coimbra, Portugal.",
                "Centro Hospitalar e Universitario de Coimbra, Departamento de Pediatria, Coimbra, Portugal.",
                "Centro Hospitalar e Universitario de Coimbra, Servico de Anestesiologia, Coimbra, Portugal.",
                "Centro Hospitalar e Universitario de Coimbra, Servico de Anestesiologia, Departamento de Pediatria, Coimbra, Portugal.",
            ],
            "LA": ["eng"],
            "PT": ["Journal Article", "Review"],
            "DEP": "20210618",
            "PL": "Brazil",
            "TA": "Braz J Anesthesiol",
            "JT": "Brazilian journal of anesthesiology (Elsevier)",
            "JID": "101624623",
            "RN": ["0 (Analgesics, Opioid)"],
            "SB": "IM",
            "MH": [
                "Abdominal Pain",
                "Adolescent",
                "Analgesics, Opioid/therapeutic use",
                "Anxiety",
                "Child",
                "*Chronic Pain/drug therapy/therapy",
                "Humans",
                "*Musculoskeletal Pain/etiology/therapy",
            ],
            "PMC": "PMC9515673",
            "OTO": ["NOTNLM"],
            "OT": [
                "Adolescent",
                "Chronic pain",
                "Pain management",
                "Pediatrics",
            ],
            "EDAT": "2021/06/22 06:00",
            "MHDA": "2022/09/14 06:00",
            "CRDT": ["2021/06/21 20:13"],
            "PHST": [
                "2020/12/17 00:00 [received]",
                "2021/04/05 00:00 [revised]",
                "2021/04/14 00:00 [accepted]",
                "2021/06/22 06:00 [pubmed]",
                "2022/09/14 06:00 [medline]",
                "2021/06/21 20:13 [entrez]",
            ],
            "AID": [
                "S0104-0014(21)00240-2 [pii]",
                "10.1016/j.bjane.2021.04.033 [doi]",
            ],
            "PST": "ppublish",
            "SO": "Braz J Anesthesiol. 2022 Sep-Oct;72(5):648-656. doi: 10.1016/j.bjane.2021.04.033. Epub 2021 Jun 18.",
        },
        {
            "PMID": "33349920",
            "OWN": "NLM",
            "STAT": "MEDLINE",
            "DCOM": "20211227",
            "LR": "20211227",
            "IS": "1526-4610 (Electronic) 0017-8748 (Linking)",
            "VI": "61",
            "IP": "2",
            "DP": "2021 Feb",
            "TI": "Remote electrical neuromodulation for acute treatment of migraine in adolescents.",
            "PG": "310-317",
            "LID": "10.1111/head.14042 [doi]",
            "AB": "OBJECTIVES: Migraine is a common disabling neurological disorder. Current acute treatments for migraine in adolescents are mostly pharmacological and may have limited effectiveness, can cause side effects, and may lead to medication overuse. There is an unmet need for effective and well-tolerated treatments. Remote electrical neuromodulation (REN) is a novel acute treatment of migraine that stimulates upper arm peripheral nerves to induce conditioned pain modulation (CPM)-an endogenous analgesic mechanism. The REN device (Nerivio((R)) , Theranica Bio-Electronics Ltd., Israel) is a FDA-authorized device for acute treatment of migraine in adults. This study assessed the efficacy and safety of REN in adolescents with migraine. DESIGN AND METHODS: This was an open-label, single-arm, multicenter study in adolescents (ages 12-17 years) with migraine. Participants underwent a 4-week run-in phase. Eligible participants continued to an 8-week treatment phase with the device. Pain severity, associated symptoms, and functional disability were recorded at treatment initiation, and 2 and 24 hours post-treatment. The primary endpoints of this study were related to the safety and tolerability of REN. The secondary endpoints were related to device efficacy and included the proportion of participants who achieved pain relief at 2 hours post-treatment and the proportion of participants who achieved pain freedom at 2 hours. The presented results reflect an interim analysis with subsequent stopping of the rest of the study. RESULTS: Sixty participants were enrolled for the study; of these, 14 failed to meet the run-in criteria and 1 was lost to follow-up. Forty-five participants performed at least one treatment, of which 39 participants completed a test treatment with REN. One device-related adverse event (2%) was reported in which a temporary feeling of pain in the arm was felt. Pain relief and pain-free at 2 hours were achieved by 71% (28/39) and 35% (14/39) participants, respectively. At 2 hours, 69% (23/33) participants experienced improvement in functional ability. CONCLUSIONS: REN may offer a safe and effective non-pharmacological alternative for acute treatment in adolescents.",
            "CI": ["(c) 2020 American Headache Society."],
            "FAU": [
                "Hershey, Andrew D",
                "Lin, Tamar",
                "Gruper, Yaron",
                "Harris, Dagan",
                "Ironi, Alon",
                "Berk, Thomas",
                "Szperka, Christina L",
                "Berenson, Frank",
            ],
            "AU": [
                "Hershey AD",
                "Lin T",
                "Gruper Y",
                "Harris D",
                "Ironi A",
                "Berk T",
                "Szperka CL",
                "Berenson F",
            ],
            "AUID": ["ORCID: 0000-0002-1598-7536"],
            "AD": [
                "Division of Neurology, Cincinnati Children's Hospital Medical Center, Cincinnati, OH, USA.",
                "Department of Pediatrics, University of Cincinnati, College of Medicine Cincinnati, Cincinnati, OH, USA.",
                "Theranica Bio-Electronics, Netanya, Israel.",
                "Theranica Bio-Electronics, Netanya, Israel.",
                "Theranica Bio-Electronics, Netanya, Israel.",
                "Theranica Bio-Electronics, Netanya, Israel.",
                "NYU Langone-Health, New York City, NY, USA.",
                "Division of Neurology, Children's Hospital of Philadelphia, Philadelphia, PA, USA.",
                "Department of Neurology, Perelman School of Medicine at the University of Pennsylvania, Philadelphia, PA, USA.",
                "Department of Pediatrics, Perelman School of Medicine at the University of Pennsylvania, Philadelphia, PA, USA.",
                "Atlanta Headache Specialists, Atlanta, GA, USA.",
            ],
            "LA": ["eng"],
            "GR": ["Theranica Bio-Electronics/"],
            "PT": ["Clinical Trial", "Journal Article", "Multicenter Study"],
            "DEP": "20201221",
            "PL": "United States",
            "TA": "Headache",
            "JT": "Headache",
            "JID": "2985091R",
            "SB": "IM",
            "MH": [
                "Acute Disease",
                "Adolescent",
                "*Analgesia/instrumentation/methods",
                "Arm/innervation",
                "Child",
                "Female",
                "Humans",
                "Male",
                "Migraine Disorders/*therapy",
                "*Nerve Fibers",
                "*Outcome Assessment, Health Care",
                "Pain Management",
                "*Peripheral Nerves",
                "Skin/innervation",
                "*Telemedicine/instrumentation/methods",
                "*Transcutaneous Electric Nerve Stimulation/instrumentation/methods",
            ],
            "OTO": ["NOTNLM"],
            "OT": [
                "Nerivio",
                "acute migraine treatment",
                "adolescents",
                "headache",
                "medication overuse headache",
                "remote electrical neuromodulation",
            ],
            "EDAT": "2020/12/23 06:00",
            "MHDA": "2021/12/28 06:00",
            "CRDT": ["2020/12/22 05:47"],
            "PHST": [
                "2020/10/05 00:00 [received]",
                "2020/11/02 00:00 [revised]",
                "2020/11/16 00:00 [accepted]",
                "2020/12/23 06:00 [pubmed]",
                "2021/12/28 06:00 [medline]",
                "2020/12/22 05:47 [entrez]",
            ],
            "AID": ["10.1111/head.14042 [doi]"],
            "PST": "ppublish",
            "SO": "Headache. 2021 Feb;61(2):310-317. doi: 10.1111/head.14042. Epub 2020 Dec 21.",
        },
        {
            "PMID": "31317889",
            "OWN": "NLM",
            "STAT": "MEDLINE",
            "DCOM": "20191002",
            "LR": "20191002",
            "IS": "1997-7298 (Print) 1997-7298 (Linking)",
            "VI": "119",
            "IP": "5",
            "DP": "2019",
            "TI": "[Tension type headaches in children and adolescents: co-morbidity with emotional and behavioral disorders].",
            "PG": "44-50",
            "LID": "10.17116/jnevro201911905144 [doi]",
            "AB": "AIM: To assess the incidence of emotional and behavioral disorders in children and adolescents with frequent episodic or chronic tension type headaches (TTH). MATERIAL AND METHODS: One hundred and fifty patients with TTH (75 boys and 75 girls), aged 8-16 years, were included in the study. The severity of emotional and behavioral problems was analyzed in comparison with their healthy peers by means of parents' interviewing with the 'Strengths and Difficulties Questionnaire' (SDQ). RESULTS: Total difficulties scores measured by SDQ were significantly higher in boys (16.2+/-0.7) and girls (14.3+/-0.7) with TTH compared with their peers (7.9+/-0.4 and 7.7+/-0.4, respectively, p<0.001). Patients with TTH had significantly more prominent manifestations than their peers (p<0.001) on the four SDQ scales, including Hyperactivity and Inattention, Conduct problems, Emotional symptoms, Peer problems. Clinical examination revealed in many pediatric patients with TTH the following disorders: attention deficit hyperactivity disorder (45.3% boys and 13.3% girls), oppositional defiant disorder (26.7% boys, 18.7% girls), with co-occurrence of both disorders in some patients (17.3% boys, 10.7% girls). Moreover, most patients with TTH had anxiety disorders (68.0% boys, 77.3% girls). CONCLUSION: Clinical features and duration of TTH may be dependent on the severity of co-morbid emotional and behavioral disorders. This should be taken into account for individualized indication of drug therapy and non-pharmacological treatment approaches in pediatric TTH.",
            "FAU": ["Shipilova, E M", "Zavadenko, N N", "Nesterovskiy, Yu E"],
            "AU": ["Shipilova EM", "Zavadenko NN", "Nesterovskiy YE"],
            "AD": [
                "Pirogov Russian National Research Medical University, Russia, Moscow.",
                "Pirogov Russian National Research Medical University, Russia, Moscow.",
                "Pirogov Russian National Research Medical University, Russia, Moscow.",
            ],
            "LA": ["rus"],
            "PT": ["Journal Article"],
            "TT": "Golovnye boli napriazheniia u detei i podrostkov: komorbidnost' s emotsional'nymi i povedencheskimi rasstroistvami.",
            "PL": "Russia (Federation)",
            "TA": "Zh Nevrol Psikhiatr Im S S Korsakova",
            "JT": "Zhurnal nevrologii i psikhiatrii imeni S.S. Korsakova",
            "JID": "9712194",
            "SB": "IM",
            "MH": [
                "Adolescent",
                "*Affective Symptoms/complications",
                "*Attention Deficit and Disruptive Behavior Disorders/complications",
                "Child",
                "Comorbidity",
                "Female",
                "Humans",
                "Male",
                "*Problem Behavior",
                "Surveys and Questionnaires",
                "*Tension-Type Headache/complications",
            ],
            "OTO": ["NOTNLM"],
            "OT": [
                "adolescents",
                "anxiety disorders",
                "attention deficit hyperactivity disorder",
                "children",
                "co-morbidity",
                "oppositional defiant disorder",
                "tension type headache",
            ],
            "EDAT": "2019/07/19 06:00",
            "MHDA": "2019/10/03 06:00",
            "CRDT": ["2019/07/19 06:00"],
            "PHST": [
                "2019/07/19 06:00 [entrez]",
                "2019/07/19 06:00 [pubmed]",
                "2019/10/03 06:00 [medline]",
            ],
            "AID": ["10.17116/jnevro201911905144 [doi]"],
            "PST": "ppublish",
            "SO": "Zh Nevrol Psikhiatr Im S S Korsakova. 2019;119(5):44-50. doi: 10.17116/jnevro201911905144.",
        },
    ]
    return record


def test_parse_result(records):
    parsed_result = parse_result(records)
    assert parsed_result.shape == (5, 7)


@pytest.mark.slow
def test_search_pubmed(query):
    records = search_pubmed(query, page_num=1, page_size=5)
    assert len(list(records)) == 5


def test_filter_split_parsed_data_into_doc_format():
    parsed_data = [
        {
            "delete": False,
            "abstract": "Sample abstract",
            "pubdate": "2021",
            "pmid": "1",
        },
        {
            "delete": True,
            "abstract": "This will be deleted",
            "pubdate": "2021",
            "pmid": "2",
        },
        {
            "delete": False,
            "abstract": "",
            "pubdate": "2021",
            "pmid": "3",
        },
        {
            "delete": False,
            "abstract": "Sample abstract",
            "pubdate": "2019",
            "pmid": "4",
        },
    ]

    expected_result = [("Sample abstract", {"source": "1"})]

    assert (
        filter_split_parsed_data_into_doc_format(parsed_data)
        == expected_result
    )
